github.com:
    users:
        Osaheneboadu:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: Osaheneboadu
